<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Siguiente</name>
   <tag></tag>
   <elementGuidId>4a2f3545-52f2-4c10-9b00-6f90989b93dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.buttons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='Contenido']/article/div/div/form/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>833482b2-d84f-4fe4-9c30-c182317d9187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>594f9a3b-64fa-4809-99f9-bd8d855a5624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Siguiente</value>
      <webElementGuid>ed8e23af-edfe-4f0a-b30f-4c7f7fad626c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Contenido&quot;)/article[1]/div[@class=&quot;contenido&quot;]/div[@class=&quot;form&quot;]/form[1]/div[@class=&quot;contenedor-buttons&quot;]/button[@class=&quot;buttons&quot;]</value>
      <webElementGuid>660322b8-8c4b-4344-afa8-b043feebb884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/div/button</value>
      <webElementGuid>4f7bb1ba-20f2-4505-862a-84bad7f85f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correo electrónico'])[1]/following::button[1]</value>
      <webElementGuid>aeb769f5-84d9-40cd-881b-8bc81e18b9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de teléfono'])[1]/following::button[1]</value>
      <webElementGuid>86f38275-f21e-4c29-8abb-0fbd1493e797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Siguiente']/parent::*</value>
      <webElementGuid>48aec64c-817e-438a-9800-55eb0c965e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e380ef32-87c1-48f3-b056-0e2dd6b49e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Siguiente' or . = 'Siguiente')]</value>
      <webElementGuid>2706e0d0-14f2-4077-b9a3-e9e5a06c51b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
