<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu actividades te llaman la atencin y_0f44fa</name>
   <tag></tag>
   <elementGuidId>7a43e4c4-eed8-4499-9800-4b84974b27d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#interes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16a5435f-223c-4cd3-810c-ea9273157759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d9dd95d-8927-4b21-8516-82f437c92456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>f7829a62-8279-4d97-b183-b18b46ef9adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>7f840774-9180-47a0-8a61-ea3ad4c5201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa actividades de tu interés</value>
      <webElementGuid>acab9718-fe06-4540-8745-d54ca7f94f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interes&quot;)</value>
      <webElementGuid>d3846279-2ceb-4302-bf09-6ca201c2a040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interes']</value>
      <webElementGuid>6410b520-a2ab-4503-a156-07237fb93b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[3]</value>
      <webElementGuid>87e21380-b3b1-48e8-92ab-7b6713a37b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>ae54685c-105c-4772-b4a3-4cac336fa352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'interes' and @name = 'interes' and @placeholder = 'Ingresa actividades de tu interés']</value>
      <webElementGuid>5048ce48-e455-46e2-a60e-84b90831f2b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
