<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellidos_apellidos</name>
   <tag></tag>
   <elementGuidId>bf5cf911-7674-48f4-8078-27b0ceab01f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apellidos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apellidos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41e390ac-f45c-4274-be68-65bad331826d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8905efaf-c6bc-4b65-993c-245fc8fe3e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apellidos</value>
      <webElementGuid>044eb630-0407-4713-94c7-0c7f9c28c22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apellidos</value>
      <webElementGuid>ee331b4f-daf8-4120-830d-0983b6ce0956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tus apellidos</value>
      <webElementGuid>b10c4a6f-327b-4d06-b195-3186951e25f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apellidos&quot;)</value>
      <webElementGuid>4615b444-d597-456d-b589-7ccc30e5b0bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apellidos']</value>
      <webElementGuid>277994fd-ff88-4736-9425-6b813fa1e53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[2]</value>
      <webElementGuid>74427ea5-4cda-4aaa-b54a-6b5876ace869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>3d828590-16a3-4990-a47c-fc548f7932b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apellidos' and @name = 'apellidos' and @placeholder = 'Ingresa tus apellidos']</value>
      <webElementGuid>039f8547-7856-4f82-bc55-b2cf8f9acfde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
