<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombres_nombres</name>
   <tag></tag>
   <elementGuidId>f0f0c6d3-3abd-4d49-a220-737310bb1053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nombres</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nombres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab0a4a47-8864-4e2a-b12d-9d3e30a2e554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e3963e8-67c4-4088-a7bc-b9391e252954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nombres</value>
      <webElementGuid>0d505cec-7d9a-4477-8a98-bce2b7720f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nombres</value>
      <webElementGuid>b6fc4d7c-a146-4da4-a558-91750da13dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tus nombres</value>
      <webElementGuid>cf6aef9f-13a0-4007-b5c4-cf277719fccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nombres&quot;)</value>
      <webElementGuid>2cc51e5b-98bf-4326-bdd0-4147570cdbee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nombres']</value>
      <webElementGuid>eec62308-4e9a-4c5c-8778-a302da76b2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input</value>
      <webElementGuid>055cec42-9200-451e-9031-34d75956a461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b91b9d44-dfd6-4c63-8c34-f83ad3d4e368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nombres' and @name = 'nombres' and @placeholder = 'Ingresa tus nombres']</value>
      <webElementGuid>438bcda8-7e44-4ce3-89d4-6d8e41b867c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
