<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cuanto tiempo le dedicas a esta activ_bf086c</name>
   <tag></tag>
   <elementGuidId>cf22a810-d535-4e5e-b641-3e848c7abb2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tiempo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tiempo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80e7b745-2417-4fc1-8cb0-29100f43ad15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a85e3191-acf3-4595-8eba-6bfe626e65db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiempo</value>
      <webElementGuid>d3330339-e519-4608-bc8b-c414d6afa3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tiempo</value>
      <webElementGuid>5cbd5148-49ea-480a-aa88-6e94f68c6313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa el tiempo, ejemplo 3-4 horas al día</value>
      <webElementGuid>e89cb508-02f6-485a-ab2f-dc76bd38a9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiempo&quot;)</value>
      <webElementGuid>6f8af7f3-7cb6-49d4-b0f7-6586ccac77be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tiempo']</value>
      <webElementGuid>9ac623d6-627e-4632-a9a3-6d5413a22b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[2]</value>
      <webElementGuid>5c13201d-5d5a-4eed-a2c0-c1aded6d5c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>d0bcbe09-7474-4459-a9b1-969a5efcc2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tiempo' and @name = 'tiempo' and @placeholder = 'Ingresa el tiempo, ejemplo 3-4 horas al día']</value>
      <webElementGuid>e7630e68-012a-4f4e-8526-70eaad497a64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
