<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cuanto tiempo le dedicas a estas acti_ea2d64</name>
   <tag></tag>
   <elementGuidId>c9e716cb-1f15-4523-828b-745001fb9b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tiempo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tiempo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99fb8e36-add0-4538-a6fc-d9828e9c2f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73221f45-8736-4426-aff0-5671d4950d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiempo</value>
      <webElementGuid>3fcfe4f6-ca6d-403f-b419-57648ac093a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tiempo</value>
      <webElementGuid>d81cc4b5-5534-4ae2-98bc-3f05ee54430a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa el tiempo, ejemplo 3-4 horas</value>
      <webElementGuid>e52d9413-2efa-4f20-a197-1846832c9478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiempo&quot;)</value>
      <webElementGuid>4c1073d4-581b-4387-90b7-bfe37d90e6e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tiempo']</value>
      <webElementGuid>887d337d-e978-4b5b-ac41-fdca75de624f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[2]</value>
      <webElementGuid>d22cc0f1-a44d-4b0f-834f-304027fba5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>c3bd548a-3409-436e-a307-2b2fe69a4074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tiempo' and @name = 'tiempo' and @placeholder = 'Ingresa el tiempo, ejemplo 3-4 horas']</value>
      <webElementGuid>a617f586-6d74-476a-a13a-3a30cef99516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
