<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cules son tus actividades favoritas_a_33a5f3</name>
   <tag></tag>
   <elementGuidId>7bf74b7d-623b-49b6-a309-67530099f213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actvidaades</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actvidaades']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00ff199a-b905-475c-9da2-6d5bbad744b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ca5b9b9-3d2b-4dae-8a79-7347a1092819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actvidaades</value>
      <webElementGuid>5685ef87-d66e-44f7-b7a6-e29331d0d9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actvidaades</value>
      <webElementGuid>61d93fa7-99fd-48f4-ae2e-54d4dea413ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tus actividades favoritas</value>
      <webElementGuid>a7572f0b-df69-48c8-b55a-bf0d473e5480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actvidaades&quot;)</value>
      <webElementGuid>040a5fb2-9017-4f48-bdf4-688bc8cbfdf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actvidaades']</value>
      <webElementGuid>40d70797-57d5-4185-b2d8-780e00131e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input</value>
      <webElementGuid>71cf6085-aaef-4c7d-b980-36a4cb4305d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2f419635-af74-41a4-b4f1-539fc483285d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'actvidaades' and @name = 'actvidaades' and @placeholder = 'Ingresa tus actividades favoritas']</value>
      <webElementGuid>64417719-ac5b-41ed-8541-7a065ac664fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
