<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu pelculas te gustan_peliculas</name>
   <tag></tag>
   <elementGuidId>a7b8893c-90d0-42ff-91d7-c510394943f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#peliculas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='peliculas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ca5e745-35da-4886-8828-ded5d54ce758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1e49e5a-9cb5-4c04-8042-abbfa0d1af43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>peliculas</value>
      <webElementGuid>89490b1a-a0d2-4821-b7b5-1079e0639986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>peliculas</value>
      <webElementGuid>3fd70ec5-7644-46da-852e-ed637224271b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa las películas que te gustan</value>
      <webElementGuid>2c74a19e-e3fb-4cf3-b82f-15d83195f308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;peliculas&quot;)</value>
      <webElementGuid>ef98748e-f7ac-495a-95c0-3d528b20f614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='peliculas']</value>
      <webElementGuid>55ef883b-6bd3-4f8d-8894-1fb68ed11c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input</value>
      <webElementGuid>7e5320e6-faf8-4a26-bb4c-75c6249ea82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>2f4f490e-e272-4681-b6a9-1290de4f12ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'peliculas' and @name = 'peliculas' and @placeholder = 'Ingresa las películas que te gustan']</value>
      <webElementGuid>bc9a89e1-43fd-4b02-b791-2feab19f30af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
