<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu juegos te llaman la atencin de pro_fd0829</name>
   <tag></tag>
   <elementGuidId>c9c52198-d68c-4477-b85b-0397d717b279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#interes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0aacd515-26d7-4814-b9d7-507f5e7b8ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd745de4-472c-4972-942a-38f907969ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>c2564e3c-0501-4747-94c8-53e718474cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>c233f6d0-2fe1-4357-95d4-35c47c75763e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa que videojuegos te llaman la atención</value>
      <webElementGuid>5fba774e-5d1d-47cc-bb5a-6c388bf30313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interes&quot;)</value>
      <webElementGuid>468b3a12-d12f-47ef-b862-fc9f709419cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interes']</value>
      <webElementGuid>b5f0a9bc-b8e2-4bbe-bbe0-8ed5f25a3746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[3]</value>
      <webElementGuid>11276823-3182-4319-9fa1-b1f10ad3a7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>960e5588-7eec-440c-ad81-53aab5f808db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'interes' and @name = 'interes' and @placeholder = 'Ingresa que videojuegos te llaman la atención']</value>
      <webElementGuid>5420c716-7f34-42aa-a1b6-92a95333d883</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
