<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Que pelculas te llaman la atencin_interes</name>
   <tag></tag>
   <elementGuidId>59725099-2ccb-4285-9355-466c601cccde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#interes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75e9d491-0125-4083-b112-8b8835e06123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8eed1dc-d168-4dbc-92d2-f4770b50ecd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>fe32fb5b-f959-42dc-a195-400f9db87177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>3329041b-7526-4665-a31b-d3518bf72459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa que películas te llaman la atención</value>
      <webElementGuid>236f1fcd-2ac8-4b94-999b-d5cd7fe11a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interes&quot;)</value>
      <webElementGuid>4f3a4b43-aab4-41ab-9ab8-6a5c71d0febc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interes']</value>
      <webElementGuid>59b8c405-632b-422d-b3a2-bb4659ec3cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[3]</value>
      <webElementGuid>90ed9086-849e-401f-8352-4c8760dcefc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>0b447389-f4da-46a6-88c6-c97e46abeab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'interes' and @name = 'interes' and @placeholder = 'Ingresa que películas te llaman la atención']</value>
      <webElementGuid>2bfc0949-b555-4602-b9fd-df011b5b2d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
