<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Que actividades te gustara dejar de h_ca3de5</name>
   <tag></tag>
   <elementGuidId>b4ccc8c5-126e-4e85-a445-1cd6e0492ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dejar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dejar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c904e25-1690-4abf-bbfa-af79e963975c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e39b2bb9-2d33-4dd6-ad26-c92f50a61378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dejar</value>
      <webElementGuid>e8b23009-d105-40de-ac5c-e055202e32d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dejar</value>
      <webElementGuid>4ccd3df6-b453-41ad-8603-f31e739629c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa las actividades que deseas dejar</value>
      <webElementGuid>7630db4e-e31b-4b35-af87-39b98a9aaf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dejar&quot;)</value>
      <webElementGuid>d270fffb-8875-45b4-8c50-9f32d1e1ec74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dejar']</value>
      <webElementGuid>a5baace2-bd67-466d-bda5-4c66264fb8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[4]</value>
      <webElementGuid>94854c17-ce89-4d12-9cc3-e70ca674bd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>911c91f9-0eaa-46e1-bfa8-0d753b456eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dejar' and @name = 'dejar' and @placeholder = 'Ingresa las actividades que deseas dejar']</value>
      <webElementGuid>f97d61aa-e99f-4476-8f67-87d6151265a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
