<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu videojuegos te gustan_juegos</name>
   <tag></tag>
   <elementGuidId>7fb5cb80-e500-46ce-adbc-9868e7c77304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#juegos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='juegos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b29ec06b-e987-4d5f-a189-ff18c7601b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a9a1749-b198-4445-9927-71e9142d7529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>juegos</value>
      <webElementGuid>7493c743-9d1f-4c55-9971-f34284a9f631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>juegos</value>
      <webElementGuid>362259bd-df65-4d38-a812-bd4e494ccafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa los videojuegos que te gustan</value>
      <webElementGuid>fe0b05ec-281d-4d4c-b59a-1f1890a7aafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;juegos&quot;)</value>
      <webElementGuid>41792609-b3b0-4e4a-9939-1332905b71d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='juegos']</value>
      <webElementGuid>5a33bda5-aa08-4dea-b18b-eb4581e40e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input</value>
      <webElementGuid>e0055c6d-afb8-4802-b9e4-17c2b586509f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>1ca4e204-7d1c-45ea-a191-cfff7307b869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'juegos' and @name = 'juegos' and @placeholder = 'Ingresa los videojuegos que te gustan']</value>
      <webElementGuid>8b37cc6a-e0fb-480c-b9a3-284847576b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
