<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Correo electrnico_correo</name>
   <tag></tag>
   <elementGuidId>6324a503-bb66-4121-ae9b-f8720ac19bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#correo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='correo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6b198d1-268e-48de-8351-8cb2bf6e509d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d79b7b06-b817-4cf9-95bf-db2390b34188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correo</value>
      <webElementGuid>84f1abe5-9320-4fa4-919f-df6159480387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>correo</value>
      <webElementGuid>a57fd956-cc7b-4246-9789-a334bb074e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tu correo electrónico</value>
      <webElementGuid>c582b889-5062-495b-b445-3580f2912a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>o</value>
      <webElementGuid>96d43b88-736f-4fea-aa8d-db386fc5d6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correo&quot;)</value>
      <webElementGuid>51f80613-9e2b-4d5a-b17d-2e84f6339671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='correo']</value>
      <webElementGuid>42bf5f4c-50a7-40fd-8014-8b64362d6580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[4]</value>
      <webElementGuid>7e4c9749-e227-42df-bdee-e1e93dc4e202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>56e45591-dd33-42ff-8faa-1a46c2be1b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'correo' and @name = 'correo' and @placeholder = 'Ingresa tu correo electrónico']</value>
      <webElementGuid>2bcbc6f8-7167-4d6b-bba1-7218eefb7ef4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
