<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Que series te llaman la atencin_interes</name>
   <tag></tag>
   <elementGuidId>32767cf1-547f-4067-baa8-70ac8b8559f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#interes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad9338fc-d380-4ccc-ad0c-32f21472ae2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c07b1867-24de-44bb-b544-09b6176d459f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>19ff8440-d1d1-4406-8dd4-6d1ada2e6853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interes</value>
      <webElementGuid>35f90ab8-7577-4ec4-b2dd-bb9c39bdc002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa que series te llaman la atención</value>
      <webElementGuid>4e58066a-d38d-46c0-a9d8-dc7c8fe166bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interes&quot;)</value>
      <webElementGuid>8d2a15e2-6dda-4995-b4d5-3235d67807af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interes']</value>
      <webElementGuid>27e23bb7-5f16-44c5-b7bd-9b7149976243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[3]</value>
      <webElementGuid>6e9e2ddd-6445-4893-b018-ea905682c6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>1eddf73a-a838-439e-938d-f86087e103d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'interes' and @name = 'interes' and @placeholder = 'Ingresa que series te llaman la atención']</value>
      <webElementGuid>cc6c4439-c873-4643-919a-0204d5da18ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
