<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de telfono_telefono</name>
   <tag></tag>
   <elementGuidId>210b1342-521a-4ead-873e-d6c58229bed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telefono</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telefono']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d09265f-0428-493f-996c-b56f03583e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>47daa45c-5811-4d3a-a3a8-bf1823c03a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telefono</value>
      <webElementGuid>b7a8d647-5a49-49ce-8913-39aac4160fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telefono</value>
      <webElementGuid>7a1fae8b-6f3b-4558-98ca-28cc79c0d0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa el número de teléfono</value>
      <webElementGuid>2fc862af-c485-48c0-bc6e-669159088107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ac25bcd-c655-4ea6-8a5a-b83128444f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telefono&quot;)</value>
      <webElementGuid>7ff5c328-22b9-4e67-80d5-76020b478b46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telefono']</value>
      <webElementGuid>84fbc6c8-3e17-432c-b34b-454043a2a716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input[3]</value>
      <webElementGuid>07c28cc1-bb05-461a-b12c-1781ff6fb442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>db553bff-14bc-476c-ba30-19a198aee2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'telefono' and @name = 'telefono' and @placeholder = 'Ingresa el número de teléfono']</value>
      <webElementGuid>253cf07b-d41b-4794-9e06-e0287caf397f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
