<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Juegos_gustar</name>
   <tag></tag>
   <elementGuidId>16237da8-ed77-4fa1-89b6-e8a80a1b7db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gustar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gustar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49028485-0f48-41f9-9661-c2f01e7b1d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c62cbf3e-257f-4c64-8f1a-a0d9a4ca254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gustar</value>
      <webElementGuid>33023c53-92ce-4fc8-a8b0-849bce47be7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gustar</value>
      <webElementGuid>04023da3-c2fa-4d9b-afba-ef3ba70c8b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Si</value>
      <webElementGuid>e07a298c-8ad2-4aac-8f09-02b7b8aa081e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Contenido&quot;)/article[1]/div[@class=&quot;contenido&quot;]/div[@class=&quot;form&quot;]/form[1]/div[@class=&quot;radios&quot;]/div[@class=&quot;radios-buttons&quot;]/input[@id=&quot;gustar&quot;]</value>
      <webElementGuid>2fa68764-6f8a-40da-ac55-4c57062ef175</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gustar']</value>
      <webElementGuid>47f704e2-4f9d-4d7a-b3d0-1dd80566998d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/div/div/input</value>
      <webElementGuid>f17bef18-d8ca-4f93-8e1a-55fa52f5f4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>049f2caf-d894-44b9-8716-5b5de9d0de0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'gustar' and @name = 'gustar']</value>
      <webElementGuid>41a2727a-db1e-4ab2-9137-bb8fa1a02e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
