<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Que series te gustan_series</name>
   <tag></tag>
   <elementGuidId>6142ceb5-68c1-4f4d-9f1c-87bdf5e5232b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#series</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='series']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ac20785-206b-49b3-8f27-cd90a896307d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>920a8459-9954-4229-aa31-27f2b47aa146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>series</value>
      <webElementGuid>6ab1cf6d-f38d-4a18-b026-fa8e3bc5b037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>series</value>
      <webElementGuid>67f7bc5f-8d76-477c-b484-4cca0bd6d977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa las series que te gustan</value>
      <webElementGuid>bce04b56-91a5-4a68-bf77-a41da20edf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;series&quot;)</value>
      <webElementGuid>f2f707c1-1ee5-459a-840f-cdf5be58cb0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='series']</value>
      <webElementGuid>e9512620-85ea-4669-ba9b-274242b28302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Contenido']/article/div/div/form/input</value>
      <webElementGuid>fe047790-1fc1-4aa0-ab6d-0237ae190c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>862995a6-1138-4683-9aed-6f7c3861020b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'series' and @name = 'series' and @placeholder = 'Ingresa las series que te gustan']</value>
      <webElementGuid>e0dad755-f1ec-4b25-9773-48df34b71514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
