<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Volver a jugar</name>
   <tag></tag>
   <elementGuidId>a0784567-97c3-4e58-9a0d-2be1a5383816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10bffa24-2be9-488d-9913-61a795d299e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volver a jugar</value>
      <webElementGuid>1788f44e-1157-4c25-8c8f-5a1e6685be93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;app&quot;]/div[@class=&quot;left-side&quot;]/button[1]</value>
      <webElementGuid>5764ec37-6a2e-4f63-b11f-dfce6c56e977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/button</value>
      <webElementGuid>9c8dc1e5-1ef9-4b5c-9a49-cd860d041abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué cantidad de huesos en el cuerpo humano?'])[1]/following::button[1]</value>
      <webElementGuid>6d4e66a9-a71a-4def-92a9-943ef9fbdcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Volver a jugar']/parent::*</value>
      <webElementGuid>cb58353d-45c9-4db1-a4be-31f911248ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6329072c-db26-4e58-bca0-c4b931f0cdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Volver a jugar' or . = 'Volver a jugar')]</value>
      <webElementGuid>bbee4fb5-82d2-43f7-bd75-fb01e0deb2f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
