<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cual es tu grado academico_question3</name>
   <tag></tag>
   <elementGuidId>3b27e0ca-937b-491a-a9de-2f8dcd3330b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dca55cee-0632-4b1e-aefd-04f167c7ffca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question3</value>
      <webElementGuid>9640a8c6-57d6-46c7-a89a-07e060dac5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3674579f-f311-470a-8a3e-b564bbfd39e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe si tu nivel academico es primario, medio, etc</value>
      <webElementGuid>9b17d298-1e08-4a46-8fa1-a0b95ac1b95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>d63bf69f-bed6-455f-8602-cd552246c5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question3&quot;)</value>
      <webElementGuid>0c0ff693-8708-4b0f-9dc7-d782c0e2519f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question3']</value>
      <webElementGuid>b93202d8-3155-469c-bea8-17977d60b59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[3]/div/input</value>
      <webElementGuid>c1acd27f-7232-4e62-8bf4-ee88ff5142d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0c5348b8-1d19-4b6e-b9e1-fcde775ea426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question3' and @type = 'text' and @placeholder = 'Escribe si tu nivel academico es primario, medio, etc']</value>
      <webElementGuid>27ce3798-f3ee-4b99-885a-066d74dfee77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
