<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sueles escuchar podcasts_question12</name>
   <tag></tag>
   <elementGuidId>48b6f660-3fc9-4d1a-a96c-0eea750d5dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42ef5a05-b079-4a4c-961e-38a247c3cbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question12</value>
      <webElementGuid>529c134c-3f87-48fb-aa1b-9c45f7b8bd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b63a3e00-e6c3-48e5-823e-bc51f22cd6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>f2810080-0364-47d8-b411-82f27dce218c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>5f0a280e-325e-4914-844f-d552b824f701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question12&quot;)</value>
      <webElementGuid>4600c6ac-5fe2-414b-ad74-db3cc09eecd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question12']</value>
      <webElementGuid>7e8bda90-1593-4229-b810-1b7be16bb75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[12]/div/input</value>
      <webElementGuid>48d0d021-a2e9-4122-8c5e-b4f2ee8db2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>c27b13ff-576f-45b8-8dc4-ca532242c81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question12' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>fba80502-4786-4993-add1-df0f705049bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
