<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cual es tu edad_question2</name>
   <tag></tag>
   <elementGuidId>0c26bfcd-5a8a-4cae-8b5f-c32b8101fabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3cffd90-9791-439d-99ac-9a6c73550fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question2</value>
      <webElementGuid>6c847ed1-5b71-47fa-bac0-5fc46a7c2d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6a460bcf-eac3-41ef-8f09-707eb08c6938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe cuantos años tienes</value>
      <webElementGuid>5ca9cc77-a692-4c44-bed2-149f673917b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>5cbfd533-564c-49f1-aa72-eb6cffe2a46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question2&quot;)</value>
      <webElementGuid>426285d0-729e-4580-9c01-389c7c3ba603</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question2']</value>
      <webElementGuid>69fe9cc5-b451-4d1d-b890-46ecde5b98c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[2]/div/input</value>
      <webElementGuid>913fd362-20a2-45d2-9148-71b87070076e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>15491c1a-7512-4140-8260-52429ade9c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question2' and @type = 'number' and @placeholder = 'Escribe cuantos años tienes']</value>
      <webElementGuid>0149a031-7e83-4ede-85fb-4c59baea84b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
