<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Te gusta escuchar musica_question4</name>
   <tag></tag>
   <elementGuidId>2799e8a9-a3c7-43fa-b3f8-85359f49a5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be23b64a-e263-4b94-9b36-9b358b5cb736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question4</value>
      <webElementGuid>4749215f-cd1d-409c-ace6-4a0f0f0298f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ebeb8ba-777c-40ce-b4bf-a5fb8124d21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>e798d5ce-2596-4d0a-a06a-e4d2951f82e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>0731cf19-5b8e-4f8b-918b-d09ba3846488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question4&quot;)</value>
      <webElementGuid>d190729c-ee99-4d2a-a52b-703bf85a0748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question4']</value>
      <webElementGuid>4bc16d3c-a6ba-41dd-9f72-5562176fad63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[4]/div/input</value>
      <webElementGuid>9c36cc13-321c-47e3-9e66-332b5a86ac6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>263da783-b2ca-4be0-9a14-22374af95cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question4' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>4f559eea-5f28-43b3-b051-af3705e8f014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
