<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Has estado en una banda anteriormente_7274a5</name>
   <tag></tag>
   <elementGuidId>963ddba8-145c-40b5-8e9e-901ac845bf2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>656188ac-f0da-4374-b13a-34c01a34fa87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question9</value>
      <webElementGuid>1c651925-6b98-4c5a-aeb7-783421247232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3ca6834-810c-4da5-a03c-e1ad3f7c3c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>79ce5b5c-f597-468a-81c5-e45495c13dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>eed1ac4b-9ddb-4794-8c69-ed62920a671f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question9&quot;)</value>
      <webElementGuid>8f3b1a5d-acee-4598-80ec-2b403ce17a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question9']</value>
      <webElementGuid>8cef453d-b2ff-4d14-bcdd-b9173b44eee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[9]/div/input</value>
      <webElementGuid>578b99a8-9dca-42c1-8557-47c60fbc1756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>38bed8dc-a7a1-42f1-9910-cf7afa7245fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question9' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>c6df7d75-0a18-4621-afde-ecb522e54e33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
