<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Si la tienes, Cual es tu apliacion fa_6815f6</name>
   <tag></tag>
   <elementGuidId>1270b2d2-f183-408c-8ed1-6f60762cd37c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca36ad82-9e5a-47be-8644-76aad085d16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question5</value>
      <webElementGuid>11290eb3-9dbb-40c9-8d59-cfb24c269b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a59ff2a8-8408-4637-b8e4-3f31afce3d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe el nombre de tu aplicacion preferida</value>
      <webElementGuid>4db2e187-bdeb-41d9-81df-d57c248a60ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>f08e12c7-b00a-439c-b18c-69256b4265c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question5&quot;)</value>
      <webElementGuid>170e0b5e-0d17-45ee-b10f-56648c278172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question5']</value>
      <webElementGuid>927ab559-638a-4106-b9a1-bca9d41fcf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[5]/div/input</value>
      <webElementGuid>7ede3875-6e69-4f83-8f7c-ac2fc4e77429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>5c533f21-944b-49af-8762-813dc37f2d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question5' and @type = 'text' and @placeholder = 'Escribe el nombre de tu aplicacion preferida']</value>
      <webElementGuid>89bab9b2-8347-4fad-a3f2-aa75fd4f908e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
