<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cual es tu artista favorito_question15</name>
   <tag></tag>
   <elementGuidId>36b53a89-73d7-4839-901c-fb9e789d9de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f416961-d6ea-46cd-aa84-baecfc83b8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question15</value>
      <webElementGuid>b5564858-7569-4123-bef9-0f7badde5939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91ef3d21-e697-484b-945b-4c2a9d81808f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe el nombre de tu artista favorito</value>
      <webElementGuid>8b51cae1-cd43-40ba-a8e5-8a94834f6129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>7ed49493-9039-4faf-8c0f-fbf2a628fb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question15&quot;)</value>
      <webElementGuid>47473095-9464-4cea-824f-74d600bf7b18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question15']</value>
      <webElementGuid>dc784026-9a43-46dc-9eb0-3d44aa1a5ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[15]/div/input</value>
      <webElementGuid>a3660996-33f1-479d-95e3-e2b5ab7937a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input</value>
      <webElementGuid>421758ee-5dee-4163-a0a8-159469bca453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question15' and @type = 'text' and @placeholder = 'Escribe el nombre de tu artista favorito']</value>
      <webElementGuid>bf95d366-c672-45d6-a4bf-f1ed88b9b676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
