<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Te gustaria aprender a tocar un instr_d03d9d</name>
   <tag></tag>
   <elementGuidId>ef7971be-259e-4bd7-b9d7-1e31e772d94f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b672e1a5-85de-412e-9328-92bc949f9b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question8</value>
      <webElementGuid>5174ac4d-585d-477e-9dec-022101e7415d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1249e53-665c-4499-ba63-b74c3cf1ee20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>914018fc-c700-4f0f-81c0-84014ddbeec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>4ac8c767-3972-4f34-8122-ead4e823e804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question8&quot;)</value>
      <webElementGuid>365cdbfc-8f88-4a13-8a85-179dd857c941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question8']</value>
      <webElementGuid>db815587-524f-4a13-b0ee-7983d2314d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[8]/div/input</value>
      <webElementGuid>6134a16e-5425-4830-9670-42d676177688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>ff82f62b-e9e3-4834-8dc7-478fadd046a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question8' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>eb8820fd-c12f-4729-8dca-3cf75816a4d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
