<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Te gusta ir a conciertos_question11</name>
   <tag></tag>
   <elementGuidId>5b12aa96-6b5f-4c88-87d7-1587b1943864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab388bb6-1b04-4ce9-9f63-cf1c38ffd726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question11</value>
      <webElementGuid>8718efcb-b664-46a6-8c39-bb572d0f2ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad7cad35-5d77-46d9-9a05-70ca686e29b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>1ed4fba4-7287-4e89-8c19-b046b527f456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>411e6e4b-0b78-468a-83bf-064aa6efa365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question11&quot;)</value>
      <webElementGuid>bee65af5-c9fe-45fa-8db5-c997b41f9b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question11']</value>
      <webElementGuid>504e9a7d-85ef-43d9-954e-2d3888f1db00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[11]/div/input</value>
      <webElementGuid>fadcb481-20f7-4600-b72e-35ddd931e010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>1f725d3b-c2eb-4f64-8aa5-690d3c4c043f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question11' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>81ff3427-c4b9-4d68-a17c-512c3fdb97f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
