<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Te gustaria escribir la letra de una _3f5be9</name>
   <tag></tag>
   <elementGuidId>e3c5a637-e55e-4f36-acd8-37c188bdf7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94dc0e78-ae71-40c5-a3d0-dee636de5994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question10</value>
      <webElementGuid>812e5964-84d0-431f-8f67-d72e4564e7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d2e9cc0-927d-48d9-bb89-9028ee11f873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>1cae1775-7f30-49de-b9d1-9c6f5a420649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>a7e9c6c9-641a-4e7b-9714-102049321d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question10&quot;)</value>
      <webElementGuid>324459f2-aace-461e-bcf0-ff2ea1f68d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question10']</value>
      <webElementGuid>ec84e9df-8fa5-419d-99ea-8547e66793d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[10]/div/input</value>
      <webElementGuid>26ab79f3-566e-4988-b592-dd53f85e5e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f938ba08-66b4-459a-a040-717d8b72531f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question10' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>aff81e16-029c-4e13-93df-a0aa47ad8b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
