<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Te gustaria aprender a hacer musica_q_2a1ec1</name>
   <tag></tag>
   <elementGuidId>f0237c45-dead-43c8-8536-fb407600f155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0e9f396-3b4a-4b04-ae50-55338fd9525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question7</value>
      <webElementGuid>d359a369-a3a3-4511-80c7-eef6c4f37c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12bb4beb-ed46-48db-a20a-1cf0523a034f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>f8dbf741-7846-4f54-a8ee-b74e624ca8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>ff273f52-9c24-4aee-8d55-74bf04ae77da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question7&quot;)</value>
      <webElementGuid>c170054c-8006-4dca-be77-e0abf3bf844b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question7']</value>
      <webElementGuid>7f5ce698-e5be-4544-ad0a-ef7140cb9997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[7]/div/input</value>
      <webElementGuid>8d9403e1-5b43-4999-98d1-5a7308faf4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>73b32ea1-7951-4b08-b722-46268fec7895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question7' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>ee0f9712-c651-475e-8a88-d93fad86d1d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
