<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cual es tu nombre_question1</name>
   <tag></tag>
   <elementGuidId>9fc344aa-ef36-4274-bc75-52e44f2d475b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>812f27b8-356f-4b2f-aeb3-f6646f858182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question1</value>
      <webElementGuid>5963a9c1-5553-475f-80c4-6c435b2ddeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d31bb5e-19df-41f1-8ffc-708bf30eebc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe tu nombre</value>
      <webElementGuid>e897f580-9249-40cf-b050-e84ebf0b296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>99507259-7f67-4568-86ac-e7222cc3e62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question1&quot;)</value>
      <webElementGuid>44feb051-4902-4a08-a229-ee27a3e0dffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question1']</value>
      <webElementGuid>a7d66c14-c7d4-43e7-8827-d4edc4dbfc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div/input</value>
      <webElementGuid>809f1663-25ad-437a-8502-40feb301775d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>deda5372-6e49-4f8d-af9b-51718e7f73d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question1' and @type = 'text' and @placeholder = 'Escribe tu nombre']</value>
      <webElementGuid>69658975-fa9e-469a-a483-e0135934ab70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
