<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cual es el genero musical que mas te _502ddc</name>
   <tag></tag>
   <elementGuidId>9c1dac9f-744e-4261-8f06-92e44bb2f7d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d081fb2-de81-47b9-a28b-b20daa3c34c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question14</value>
      <webElementGuid>33e33a5d-62b8-4496-a806-cffd195af43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e56aeb25-d5db-423c-8381-f4b090df6a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe el nombre de tu genero musical favorito</value>
      <webElementGuid>91602f19-4e08-4137-979d-b1864d3cd909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>d335a4b6-18c3-4073-be29-03348c78f1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question14&quot;)</value>
      <webElementGuid>eba5d086-c66c-46da-8110-2ff72e54ef4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question14']</value>
      <webElementGuid>a5d99dc2-8242-4fbd-b6ba-202970776eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[14]/div/input</value>
      <webElementGuid>05c36095-2d1e-41e7-99c2-bb0386aa2b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input</value>
      <webElementGuid>6b140f0c-3a35-4b23-8a73-f41065428a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question14' and @type = 'text' and @placeholder = 'Escribe el nombre de tu genero musical favorito']</value>
      <webElementGuid>a9be5bee-d1fc-452a-96e8-cf5276abee0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
