<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Que tan frecuentemente escuchas music_8c5fea</name>
   <tag></tag>
   <elementGuidId>5ee51289-f437-409c-9220-29ac82f4cf6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7050c1e9-fa1d-4ea6-a451-68215d9fd311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question6</value>
      <webElementGuid>f32598fe-0d5f-4c58-be5e-902cc64aff78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b8e980a-42ac-4b0a-b152-0bb330574e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe la frecuencia con la que escuchas musica</value>
      <webElementGuid>fa90e87a-79e3-4402-82d7-b5ff0a9e3a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>71ced567-0a9e-4c96-ada5-b1f934f7b826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question6&quot;)</value>
      <webElementGuid>4ac8064d-4120-4a6f-8fe0-2ca26826e0b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question6']</value>
      <webElementGuid>cf09ba7d-296f-4f60-9ac5-ec02048598d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[6]/div/input</value>
      <webElementGuid>b4914abb-8104-4a01-a539-c7ba0fe4eb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>f0efde57-8c27-44bd-8bd2-886a96a2945c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question6' and @type = 'text' and @placeholder = 'Escribe la frecuencia con la que escuchas musica']</value>
      <webElementGuid>baa92b21-e319-413e-b7dc-e595b9625e72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
