<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Te gusta escuchar musica mientras tra_ca246b</name>
   <tag></tag>
   <elementGuidId>a83e3f2f-973a-4dfe-9c17-544245e447e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>128fbf16-d214-46e7-a685-ce0274341faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question13</value>
      <webElementGuid>583633ef-dbb4-4d2b-86d3-5eeeb2647c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>563b3d4e-f340-4bc1-948a-7de28b6237a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe Si o No</value>
      <webElementGuid>ba93a754-b6d7-4ce5-a706-48c302001358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textSpace</value>
      <webElementGuid>bc4b0140-a18b-45e2-b4e1-118512b206e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question13&quot;)</value>
      <webElementGuid>b580c7e2-83c7-4b01-a5b0-a579ef314b62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question13']</value>
      <webElementGuid>61636848-fd9c-4c71-b414-f04c9f332509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[13]/div/input</value>
      <webElementGuid>88e03e19-35ef-46e4-9b11-6973997766fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>55f8ff64-f779-4866-9b3a-d6640d01c10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'question13' and @type = 'text' and @placeholder = 'Escribe Si o No']</value>
      <webElementGuid>66202e5c-58f9-48a7-bbb7-741412bf1056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
