<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vamos</name>
   <tag></tag>
   <elementGuidId>ac73fa77-1319-4eac-9586-ebd9e71d89bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.form__submit-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10918496-556e-44a4-806a-5074a268d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__submit-home</value>
      <webElementGuid>4db029ee-8c8a-42ae-9a0b-44e051f2e8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/step1</value>
      <webElementGuid>62983a1f-879b-4f74-aa10-a12cd472b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡Vamos!</value>
      <webElementGuid>3ab7c9cb-feee-47d2-a886-6a995f39106c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;form__home&quot;]/div[1]/a[@class=&quot;form__submit-home&quot;]</value>
      <webElementGuid>c4970043-2fbb-4dc0-bb31-c8fd0877cd8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/a</value>
      <webElementGuid>e8213381-54f4-4e4b-8965-1bce01279370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'¡Vamos!')]</value>
      <webElementGuid>df713414-325f-4a4b-b940-56e9d9b64dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenido'])[1]/following::a[1]</value>
      <webElementGuid>be1b967c-b395-4697-b243-249070a63546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gastos'])[1]/following::a[1]</value>
      <webElementGuid>52604719-3ac4-4896-8184-f6a1206c1b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡Vamos!']/parent::*</value>
      <webElementGuid>79334ee0-337a-434c-a5f4-66cf71737dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/step1')])[2]</value>
      <webElementGuid>9af800cf-7226-4ceb-8d76-0b0e5df7eda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>243d29a5-235c-48b2-b8f5-2cf9deb87329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/step1' and (text() = '¡Vamos!' or . = '¡Vamos!')]</value>
      <webElementGuid>0734b670-b294-472d-9fb8-a9d464676700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
